apiVersion: batch/v1
kind: CronJob
metadata:
  name: newapi
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
				metadata:
					labels:
						type: cronjob
        spec:
          containers:
          - name: hello
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - sleep 90
          restartPolicy: OnFailure
